### ISSUE TITLE
OPENSHIFT_TARGET value question

### ISSUE THREAD

**Issue by akarasev** [ansibleplaybookbundle/Hello-World-APB#4]
How does the value of the variable `OPENSHIFT_TARGET` look like?

Whatever value I tried, I always have:
> TASK [provision-hello-world-apb : create deployment config] ********************
fatal: [localhost]: FAILED! => {"changed": false, "error": null, "msg": "Failed to retrieve requested object: <urllib3.connection.VerifiedHTTPSConnection object at 0x4048650>: Failed to establish a new connection: [Errno 111] Connection refused"}

I tried my OpenShift Origin TCP addresses: `192.168.42.174:8443` and `https://192.168.42.174:8443`

**Comment by djzager** [comment]
This apb has changed a great deal since March 6th. In particular, you no longer need to set the `OPENSHIFT_TARGET`. The [readme](README.md) now instructs, if using `docker run`, to simply share your `~/.kube` dir as a volume into the container.
